### ISSUE TITLE
Seems to be cutting names short

### ISSUE THREAD

**Issue by jhchrist** [yesokcool/ALE#3]
Sometimes the player name will be cut off near the end, the start, or both ends. Not sure why yet. Neat program tho, should save me some time. ty

**Comment by yesokcool** [comment]
Thanks for bringing this to my attention. Would it be possible to send: 

1. the name that this is occurring with (can change the middle letters to censor if needed)
2. the ALE options that are checked / unchecked when this happens (screenshot works)
3. a copy + pasted line from the ALE output where it occurs (you can censor the message if needed) and the output you expected instead
